dist: xenial
language: c++
compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install openjdk-8-jdk
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install bazel -y
  - sudo apt-get install libsdl2-dev 
  - sudo apt-get install libgoogle-perftools-dev 

script:
  - bazel test -c opt //...
  - bazel test -c dbg //...
  - bazel test -c dbg --config=asan //...
