[package]
name = "spout"
version = "0.1.0"
authors = ["Geoffrey Lalonde <lalondegeoffrey@gmail.com>"]
edition = "2018"
resolver = "2"

[profile.release]
debug = true

[features]
default = []
music = ["rodio"]

[dependencies]
gflags = "0.3"
winit = "0.26" 
log = "0.4"
wgpu = "0.12"


[dev-dependencies]
bytemuck = { version = "1.4", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
async-executor = "1.0"
pollster = "0.2"
scrub_log = "0.2"

[dependencies.rodio]
git = "https://github.com/RustAudio/rodio" 
default-features = false
features = ["vorbis", "flac", "wav"]
optional = true
