[package]
name = "spout"
version = "0.1.0"
authors = ["Geoffrey Lalonde <lalondegeoffrey@gmail.com>"]
edition = "2018"

[profile.release]
debug = true

[features]
default = []

[dependencies]
image = "0.23"
gflags = "0.3"
winit = { version = "0.22", features = ["web-sys"] }
scrub_log = "0.2"
log = "0.4"
wgpu = "0.6"
walkdir = "2.2.9"
lazy_static = "*"
zerocopy = "0.2"
cgmath = "0.17"
rand = "0.7"
png = "0.15"
scarlet = "1.1.0"
wgpu_glyph = "0.10"
futures = { version = "0.3", features = ["thread-pool"] }
rodio = { git = "https://github.com/RustAudio/rodio" , default-features = false, features = ["vorbis", "flac", "wav"] }
crossbeam-channel = "0.4"
rust-embed = { version = "5.5", features = ["interpolate-folder-path"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
anyhow = "1.0"

[build-dependencies]
log = "*"
shaderc = "*"
walkdir = "2.2.9"
phf = {version = "0.8.0", features = ["macros"]}
scrub_log = "0.2"