name: CI

on:
  push:
    branches-ignore: [ staging.tmp ]
  pull_request:
    branches-ignore: [ staging.tmp ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04, windows-2019]
    steps:
    - uses: actions/checkout@v2
    - name: Cargo check
      run: cargo check

    - uses: actions/checkout@v2
    - name: Cargo test
      run: cargo test --no-run
