package(default_visibility = ["//visibility:public"])
load("//vulkan:glsl_to_spirv.bzl", "glsl_to_spirv")

glsl_to_spirv(
    name = "frag_shader",
    main = "shader.frag",
    )

glsl_to_spirv(
    name = "vert_shader",
    main = "shader.vert",
    )
