#version 430
#extension GL_GOOGLE_include_directive : enable
#include "particle.h"

// Iterate over all of the particles and atomically aggregate them on the output `counter_texture`

layout (binding = 0, r32ui) uniform uimage2D counter_texture;
layout(std430, binding = 0) readonly buffer Particles {
  Particle particles[];
};

void main() {
  uint gid = gl_GlobalInvocationID.x;
  ivec2 image_coord = ivec2(particles[gid].position);
  imageAtomicAdd(counter_texture, image_coord, 1);
}