name: github pages

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  RUSTFLAGS: --cfg=web_sys_unstable_apis

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Install WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli --version 0.2.114 --locked

      - name: Build WebGPU
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Generate JS bindings for WebGPU examples
        run: wasm-bindgen --no-typescript --out-dir target/spout_web --web target/wasm32-unknown-unknown/release/spout.wasm

      - name: Write html
        run: cat wasm-resources/index.template.html | sed "s/{{example}}/spout/g" > target/spout_web/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/spout_web